config/routes.rb
CoCCalc::Application.routes.draw do
  resources :troops

  root to: "welcome#index"
end

app/models/troop.rb
class Troop < ActiveRecord::Base
	validates :level, presence: true,
		length: { in: 0..9 }
	validates :quantity, presence: true,
		length: { in: 0..9 }
	validates :typeoftroop, presence:true
	validates :typeoftroop, uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/troops_controller.rb
class TroopsController < ApplicationController
	def new
	  @troop = Troop.new
	end

	def create
		@troop = Troop.new(params[:troop].permit(:typeoftroop, :level, :quantity, :costToTrain))
		if @troop.save
			redirect_to @troop
		else
			render 'new'
		end
	end

	def show
	  @troop = Troop.find(params[:id])
	end

	def index
	  @troops = Troop.all
	end

	def edit
	  @troop = Troop.find(params[:id])
	end

	def update
	  @troop = Troop.find(params[:id])

	  if @troop.update(params[:troop].permit(:typeoftroop, :level, :quantity, :costToTrain))
	    redirect_to @troop
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @troop = Troop.find(params[:id])
	  @troop.destroy

	  redirect_to troops_path
	end

	private
	  def troop_params
	    params.require(:troop).permit(:typeoftroop, :level, :quantity)
	  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/troops_helper.rb
module TroopsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoCCalc</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/troops/_form.html.erb
<%= javascript_include_tag('math') %>

<%= form_for @troop do |f| %>
  <% if @troop.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@troop.errors.count, "error") %> prohibited
      this troop from being saved:</h2>
    <ul>
    <% @troop.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<!-- <p>
  <%= f.label :Type_Of_Troop %><br>
  <%= f.text_field :typeoftroop %>
</p> -->

<div class="row-fluid">
  <div class="col-lg-6">
    <select id = "typeSelect">
      <option value="Barbarian" selected="selected">Barbarian</option>
      <option value="Archer">Archer</option>
      <option value="Goblin">Goblin</option>
      <option value="Giant">Giant</option>
      <option value="Wall Breaker">Wall Breaker</option>
      <option value="Balloon">Balloon</option>
      <option value="Wizard">Wizard</option>
      <option value="Healer">Healer</option>
      <option value="Dragon">Dragon</option>
      <option value="PEKKA">PEKKA</option>
    </select>
    <br><br>
    <%= f.label :level %><br>
    <%= f.text_field :level %>
    <br>
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
    <br>
    <%= f.label :Training_Cost %><br>
    <%= f.text_field :costToTrain %>
  </div>
  <div class="col-lg-6">
    <div class="row-fluid">
      <div class="col-lg-12 text-center">
        <%= f.submit "Add Troop", :class=> "btn btn-success" %>
      </div>
    </div>
    <div class="row-fluid">
      <div class="col-lg-12 text-center" style="margin-top: 20px;">
        <%= link_to 'Back', troops_path, :class=>"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
<p id="hiddenTroopType">
  <%= f.text_field :typeoftroop %>
</p>
<script>
$('document').ready(function(){
  $('#hiddenTroopType').hide();
})
  $('[type="text"]').change(function(){
    var typeTroop = $('#typeSelect').val();
    var levTroop = parseInt($('#troop_level').val());
    var quantityTroops = parseInt($('#troop_quantity').val());
    var finalCost = calcCost(typeTroop, levTroop, quantityTroops);
    $('#troop_costToTrain').val(finalCost);
    $('#troop_typeoftroop').val($('#typeSelect').val());
  });
</script>
<% end %>

app/views/troops/edit.html.erb
<h1>Editing Troops</h1>
 
<%= render 'form' %>

<%= link_to 'Back', troops_path %>

app/views/troops/index.html.erb
<%= javascript_include_tag('math') %>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Clan Calculator</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a target="_blank" href="http://www.clashofclansbuilder.com">Base Builder</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<body>
  <div class="container">
    <h1>Your Army</h1>
    <div class="row-fluid">
      <div class="col-lg-10">
        <table class="table table-striped">
          <tr align="center">
            <th class="text-center">Type</th>
            <th class="text-center">Level</th>
            <th class="text-center">Quantity</th>
            <th class="text-center">Cost To Train</th>
            <th class="text-center">Actions</th>
          </tr>
          <% @troops.each do |troop| %>
            <tr align="center">
              <td align="center"><%= troop.typeoftroop %></td>
              <td align="center"><%= troop.level %></td>
              <td align="center"><%= troop.quantity %></td>
              <td align="center"><%= troop.costToTrain %></td>
              <td align="center">
                <div class="btn-group btn-group-sm">
                  <%= link_to 'View', troop, :class=> "btn btn-info btn-sm" %>
                  <%= link_to 'Edit', edit_troop_path(troop), :class=> "btn btn-warning btn-sm" %>
                  <%= link_to 'Delete', troop_path(troop),
                  method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-sm" %>
                </div>
              </td>
            </tr>
          <% end %>
      </table>
      </div>
      <div class="col-lg-2">
        <div class="row-fluid">
          <div class="col-lg-12 text-center">
              <%= link_to 'New troop', new_troop_path, :class=> "btn btn-success" %>
            </button>
          </div>
        </div>
        <hr>
        <div class="row-fluid">
          <div class="col-lg-12 text-center">
            The total cost to train all your troops is: <strong><%= Troop.sum("costToTrain") %></strong>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/troops/new.html.erb
<%= javascript_include_tag('math') %>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Clan Calculator</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a target="_blank" href="http://www.clashofclansbuilder.com">Base Builder</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<body>
	<div class="container">
  		<h1>T-R-Double O-Pizzles</h1>
  		<%= render 'form' %>
	</div>
</body>

app/views/troops/show.html.erb
<%= javascript_include_tag('math') %>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Clan Calculator</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a target="_blank" href="http://www.clashofclansbuilder.com">Base Builder</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<body>
	<div class="container">
  		<h1>Newest ready to ride or die troops</h1>
  		<div class="row-fluid">
  			<div class="col-lg-12">
  				<strong>Type:</strong>
  				<%= @troop.typeoftroop %>
			</div>
			<div class="col-lg-12">
  				<strong>Quantity:</strong>
  				<%= @troop.level %>
			</div>
			<div class="col-lg-12">
  				<strong>Level:</strong>
  				<%= @troop.quantity %>
			</div>
			<div class="col-lg-12" style="margin-bottom: 20px">
  				<strong>Cost To Train:</strong>
  				<%= @troop.costToTrain %>
			</div>
			<%= link_to 'Back', troops_path, :class=> "btn btn-info" %>
		</div>
	</div>
</body>

app/views/welcome/index.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Clan Calculator</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a target="_blank" href="http://www.clashofclansbuilder.com">Base Builder</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<body>
	<div class="container">
		<div class="text-center">
			<h1>Let's go to war!</h1>
			<p>Raiding is expensive. How many troops you use determines whether or not the raid is profitable</p>
			<hr>
			<%= link_to "Troop Calculator", controller: "troops" %>
		</div>
	</div>
</body>